### ISSUE TITLE
Reload导致复读机

### ISSUE THREAD

**Issue by XieXiLin158** [MeowCat-Studio/kato-message-source#6]
要是在服务器reload后会导致复读机.jpg
图：实践出真相

**Comment by Itsusinn** [comment]
@XieXiLin158 请不要使用热重载

**Comment by Itsusinn** [comment]
以修复，以下内容节选自commit
> 严重警告: 介于jvm的追踪式GC,某些静态声明的变量可能无法被释放，有引起内存泄露的可能

**Comment by XieXiLin158** [comment]
@Itsusinn 不不不，有时候必须热重载，不然会影响玩家.jpg
